package https.bezbednost;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-09-01T18:14:10.858+02:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "https://bezbednost/", name = "SmestajServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface SmestajServiceSoap {

    @WebMethod
    @RequestWrapper(localName = "saveSmestajSlika", targetNamespace = "https://bezbednost/", className = "https.bezbednost.SaveSmestajSlika")
    @ResponseWrapper(localName = "saveSmestajSlikaResponse", targetNamespace = "https://bezbednost/", className = "https.bezbednost.SaveSmestajSlikaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public https.bezbednost.SmestajSlika saveSmestajSlika(
        @WebParam(name = "arg0", targetNamespace = "")
        https.bezbednost.SmestajSlika arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findSmestajById", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindSmestajById")
    @ResponseWrapper(localName = "findSmestajByIdResponse", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindSmestajByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public https.bezbednost.Smestaj findSmestajById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findTerminById", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindTerminById")
    @ResponseWrapper(localName = "findTerminByIdResponse", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindTerminByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public https.bezbednost.Termin findTerminById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findAllServices", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindAllServices")
    @ResponseWrapper(localName = "findAllServicesResponse", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindAllServicesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<https.bezbednost.DodatnaUsluga> findAllServices();

    @WebMethod
    @RequestWrapper(localName = "findAllRezervacije", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindAllRezervacije")
    @ResponseWrapper(localName = "findAllRezervacijeResponse", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindAllRezervacijeResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<https.bezbednost.Rezervacija> findAllRezervacije();

    @WebMethod
    @RequestWrapper(localName = "findAllNaseljenoMesto", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindAllNaseljenoMesto")
    @ResponseWrapper(localName = "findAllNaseljenoMestoResponse", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindAllNaseljenoMestoResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<https.bezbednost.NaseljenoMesto> findAllNaseljenoMesto();

    @WebMethod
    @RequestWrapper(localName = "findAllCategories", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindAllCategories")
    @ResponseWrapper(localName = "findAllCategoriesResponse", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindAllCategoriesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<https.bezbednost.Kategorija> findAllCategories();

    @WebMethod
    @RequestWrapper(localName = "findNaseljenoMestoById", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindNaseljenoMestoById")
    @ResponseWrapper(localName = "findNaseljenoMestoByIdResponse", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindNaseljenoMestoByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public https.bezbednost.NaseljenoMesto findNaseljenoMestoById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findSlikaById", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindSlikaById")
    @ResponseWrapper(localName = "findSlikaByIdResponse", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindSlikaByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public https.bezbednost.SmestajSlika findSlikaById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findKomentarById", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindKomentarById")
    @ResponseWrapper(localName = "findKomentarByIdResponse", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindKomentarByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public https.bezbednost.Komentar findKomentarById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findTipById", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindTipById")
    @ResponseWrapper(localName = "findTipByIdResponse", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindTipByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public https.bezbednost.TipSmestaja findTipById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findAllAccomodations", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindAllAccomodations")
    @ResponseWrapper(localName = "findAllAccomodationsResponse", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindAllAccomodationsResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<https.bezbednost.Smestaj> findAllAccomodations();

    @WebMethod
    @RequestWrapper(localName = "save", targetNamespace = "https://bezbednost/", className = "https.bezbednost.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "https://bezbednost/", className = "https.bezbednost.SaveResponse")
    @WebResult(name = "return", targetNamespace = "")
    public https.bezbednost.Smestaj save(
        @WebParam(name = "arg0", targetNamespace = "")
        https.bezbednost.Smestaj arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findDodatnaUslugaById", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindDodatnaUslugaById")
    @ResponseWrapper(localName = "findDodatnaUslugaByIdResponse", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindDodatnaUslugaByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public https.bezbednost.DodatnaUsluga findDodatnaUslugaById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod
    @RequestWrapper(localName = "saveTermin", targetNamespace = "https://bezbednost/", className = "https.bezbednost.SaveTermin")
    @ResponseWrapper(localName = "saveTerminResponse", targetNamespace = "https://bezbednost/", className = "https.bezbednost.SaveTerminResponse")
    @WebResult(name = "return", targetNamespace = "")
    public https.bezbednost.Termin saveTermin(
        @WebParam(name = "arg0", targetNamespace = "")
        https.bezbednost.Termin arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findKategorijaById", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindKategorijaById")
    @ResponseWrapper(localName = "findKategorijaByIdResponse", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindKategorijaByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public https.bezbednost.Kategorija findKategorijaById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findZauzetostById", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindZauzetostById")
    @ResponseWrapper(localName = "findZauzetostByIdResponse", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindZauzetostByIdResponse")
    @WebResult(name = "return", targetNamespace = "")
    public https.bezbednost.Zauzetost findZauzetostById(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findAllTypes", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindAllTypes")
    @ResponseWrapper(localName = "findAllTypesResponse", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindAllTypesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<https.bezbednost.TipSmestaja> findAllTypes();

    @WebMethod
    @RequestWrapper(localName = "getSmestajeAgenta", targetNamespace = "https://bezbednost/", className = "https.bezbednost.GetSmestajeAgenta")
    @ResponseWrapper(localName = "getSmestajeAgentaResponse", targetNamespace = "https://bezbednost/", className = "https.bezbednost.GetSmestajeAgentaResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<https.bezbednost.Smestaj> getSmestajeAgenta(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );
}
