package https.bezbednost;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-09-03T10:59:05.658+02:00
 * Generated source version: 3.2.4
 *
 */
@WebService(targetNamespace = "https://bezbednost/", name = "UserServiceSoap")
@XmlSeeAlso({ObjectFactory.class})
public interface UserServiceSoap {

    @WebMethod
    @RequestWrapper(localName = "verifyAgentLogin", targetNamespace = "https://bezbednost/", className = "https.bezbednost.VerifyAgentLogin")
    @ResponseWrapper(localName = "verifyAgentLoginResponse", targetNamespace = "https://bezbednost/", className = "https.bezbednost.VerifyAgentLoginResponse")
    @WebResult(name = "return", targetNamespace = "")
    public https.bezbednost.User verifyAgentLogin(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "findOne", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindOne")
    @ResponseWrapper(localName = "findOneResponse", targetNamespace = "https://bezbednost/", className = "https.bezbednost.FindOneResponse")
    @WebResult(name = "return", targetNamespace = "")
    public https.bezbednost.User findOne(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.Long arg0
    );
}
